### PR TITLE
Latest style/look changes and transformation file.

### PR DESCRIPTION
**Pull request by johndotpy**

### CODE REVIEW

**Comment by archaeogeek** [comment]
Hey John, this pull request is too big for me to inspect and review on github unfortunately (it changes 227 files!). I also can't merge it automatically, so it's going to take some time to review. In future, can you do a pull request per commit?

**Comment by johndotpy** [comment]
Hi Jo,

Sorry - learning! Ignore the Syncing - that was me trying to get my fork up to date as it was before the reorganization with the folders. I don't know why it did that, I'm sure I am at error. It is only the JT Edits that require verifying. Not sure if that helps.

**Comment by archaeogeek** [comment]
No probs, I'll take a look through it tomorrow- I don't get to pick and choose what I accept, unfortunately, but hopefully all will be fine

**Comment by archaeogeek** [comment]
Done, hopefully I caught all the conflicts!

**Pull request merged**
